### ISSUE TITLE
MRR

### ISSUE THREAD

**Issue by pminervini** [snap-stanford/KGReasoning#1]
Hello, love this project! :)

A quick question: Tab. 8 in https://arxiv.org/pdf/2002.05969.pdf (Q2B paper) shows some MRR results for GQE and Q2B, but the MRR values from Tab. 1 in https://arxiv.org/pdf/2010.11465.pdf (BetaE paper) look a bit different - is there a different evaluation protocol being used?

**Comment by nxznm** [comment]
It seems like BetaE constructs new queries and it is evaluated on both the queries in Q2B (Tab. 10 in BetaE paper) and the new realistic queries (Tab. 1 in BetaE paper), the reason is clarified in Sec 5.1.

**Comment by hyren** [comment]
Hi, sorry for the late reply! Yes just as @nxznm said, we evaluate BetaE on two different test sets. And you can check the results of the test queries from the Q2B paper in Table 10. Note that we also improved the implementation of Q2B so that the current results are slightly higher than the original results reported in the Q2B paper. Let me know if you have any further questions and I would love to help.
