### ISSUE TITLE
Natural Queries Extraction

### ISSUE THREAD

**Issue by ashispapu** [snap-stanford/KGReasoning#10]
Thanks for sharing the repo. 
I'm trying to find/extract the natural language queries of the respective entity and relation represented queries. Could you share if it is available or could be extracted. Any reference would be helpful.

**Comment by hyren** [comment]
Thanks for your interest. This repo assumes that the input to the system is the query in a structured/logic form. I will close this issue since this is irrelevant to this repo. 

To give you a few pointers, we have a recent [work](http://proceedings.mlr.press/v139/ren21a.html) that directly takes the natural language question as input and tries to parse it into logical form and embed it for answers. Feel free to send me an email if you have any question about this work. Besides, you can also check [spaCy](https://spacy.io/api/entitylinker) for entity linking.

**Comment by ashispapu** [comment]
Thank you for the response and pointers. I tried to visit the below repo of LEGO, however did not find the implementation.
http://github.com/snap-stanford/lego

**Comment by hyren** [comment]
Hi, we are cleaning the code and it will be released soon. Stay tuned.

**Comment by ashispapu** [comment]
Thanks for the update
